### PR TITLE
use api for data retrieval

### LINKED ISSUE #1: SN stream stage QC via API
@fostermh @boshek created issue to track changes to sn stage qc script. Currently not working and unable to upload via the API.  Would like to query specific date ranges and sensor sites.

### PR DESCRIPTION
**Pull request by boshek**
This converts this script to using the API for data retrieval. Will close #1 

Note that this:
- has a small date range from 2016
- is still using goose for testing
- note the `limit=-1` which overrides the api limits for how much data you request. This limit is in place to prevent massive pulls of data so something to be aware of.

### CODE REVIEW

File: stage/stage-qc.R [hunk 1]
```diff
@@ -1,19 +1,55 @@
...
 # Step 2: Apply linear interpolation for small gaps (<12)
 df <- df %>%
-  arrange(timestamp) %>%
+  arrange(measurementTime) %>%
   mutate(
-    stage_filled = zoo::na.approx(stage, x = timestamp, maxgap = 12, na.rm = FALSE),
+    stage_filled = zoo::na.approx(stage, x = measurementTime, maxgap = 12, na.rm = FALSE),
     qflag = case_when(
       is.na(stage) & !is.na(stage_filled) ~ "EV_LINEAR",  # Linear fill
       TRUE ~ qflag
```
Comment (fostermh) [inline stage/stage-qc.R]: you might need to cast qflag to a character vector in cases where qflag is already set as R seems to think it's a number column. `TRUE ~ as.character(qflag)`

**Review by fostermh — APPROVED** [review]

File: stage/stage-qc.R (hunk 1 above)
Comment (boshek) [reply stage/stage-qc.R]: Ah good catch. Yeah if that condition isn't met that qflag could be any type at all.

Comment (boshek) [reply stage/stage-qc.R]: fixed in https://github.com/HakaiInstitute/wx-tools/pull/2/commits/d04d72a89c97ef68fbe788e792adc1dd4c4c31f0
